apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang
spec:
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
        - name: golang
          image: imgabreuw/imersao-fullcycle-6-golang:latest
          envFrom:
            - secretRef:
                name: golang-secret
